---
title: "ROI_analyses"
author: "Laura Giglio"
date: "January 15, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(plyr)
library(dplyr)
library(tidyverse)
library(plotrix)
library(reshape2)
rm(list=ls())
#setwd("P:/3011226.01/behavioural/")
packages <- c("ggplot2", "dplyr", "lavaan", "plyr", "cowplot", "rmarkdown", 
              "readr", "caTools", "bitops")
if (length(setdiff(packages, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(packages, rownames(installed.packages())))  
}
library(cowplot)
library(dplyr)
library(readr)

source("C:/Users/laugig/Documents/RainCloudPlots-master/RainCloudPlots-master/tutorial_R/R_rainclouds.R")
#source("summarySE.R")
#source("simulateData.R")
```

## ROI plots

Table includes averaged beta values per participant per ROI. msXX specifies condition in IFG. TmsXX condition in MTG. First number 1 is production, 2 is comprehension, Second 1 is NP, 2 SC, 3 SE

```{r import ROI data, echo = FALSE}

ROIbetas = read.table("P:/3011226.01/bids/derivatives/SPM/ROI/ROIresults.csv", header = T, sep = ',')

ROIbetas$participant = as.factor(ROIbetas$participant)

#tranform in long format
ROI_betas = melt(ROIbetas, id.vars=c('participant'), variable.name='condition_ROI',value.name='betas')

```

## Including Plots


```{r plots, echo=FALSE}

mean_betas <- ROI_betas %>% group_by(condition_ROI) %>% summarise(meanBetas = mean(betas),sdBetas = sd(betas),N=n())

for (icond in 1:12) {
  mean_betas$structure[icond] = unlist(strsplit(as.character(mean_betas$condition_ROI[icond]), "_"))[2]
  mean_betas$ROI[icond] = unlist(strsplit(as.character(mean_betas$condition_ROI[icond]), "_"))[1]
  mean_betas$condition[icond] = unlist(strsplit(as.character(mean_betas$condition_ROI[icond]), "G_"))[2]
}

mean_betas$modality = ifelse(endsWith(as.character(mean_betas$condition),'P'),'Production','Comprehension')

## use SD & N to create error bars for standard error of the mean
mean_betas$CIu <- mean_betas$meanBetas + (mean_betas$sdBetas/sqrt(mean_betas$N)) 
mean_betas$CId <- mean_betas$meanBetas - (mean_betas$sdBetas/sqrt(mean_betas$N))



ROI_bar = ggplot(mean_betas, aes(x=condition, y=meanBetas,fill = modality)) + geom_bar(stat='identity') +
  geom_errorbar(aes(ymax=CIu,ymin=CId),width=.1) +
  facet_grid(~as.factor(ROI))+
  scale_y_continuous("Parameter Estimates")
ggsave('P:/3011226.01/bids/derivatives/SPM/ROI/ROI_bar.pdf')

ROI_bar

```

```{r violin plot, echo=FALSE}

p7 <- ggplot(ROI_betas,aes(x=Condition,y=Betas))+
  geom_flat_violin(position = position_nudge(x = .25, y = 0),adjust =2, alpha=0.3)+
  geom_point(position = position_jitter(width = .15), size = .25, aes(color = participant))+
  #note that here we need to set the x-variable to a numeric variable and bump it to get the boxplots to line up with the rainclouds. 
  #geom_boxplot(aes(x = as.numeric(Condition)+0.25, y = Onset),outlier.shape = NA, alpha = 0.3, width = .1, colour = "BLACK") +
  ylab('Onset')+xlab('Condition')+theme_cowplot() +
  ggtitle("Onset times per condition")

p7
```

```{r stats, echo=FALSE}


```
Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
